FROM oven/bun:latest

WORKDIR /app

# Copy package.json and bun.lockb
COPY frontend/package.json frontend/bun.lockb ./

# Install dependencies
RUN bun install

# Copy the rest of the frontend code
COPY frontend/ ./

ENV NEXT_TELEMETRY_DISABLED 1

# Expose the port the app runs on
EXPOSE 5173

CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
