version: "3.8"

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.17
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text-embedding-3-small"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "6789:5678"
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL=http://weaviate:8080

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      # - "3000:3001"
      - "5180:3001" # Map container port 5173 to host port 5180
    depends_on:
      - backend
    environment:
      # - REACT_APP_BACKEND_URL=http://localhost:6789
      - REACT_APP_BACKEND_URL=http://18.204.9.187:6789 # Ensure this is the correct IP and port for backend

volumes:
  weaviate_data:
    driver: local
